mortality <- read.csv(file.choose(), header = TRUE)
attach(mortality)
#1 Forward Selection
mortality_precip <- lm(Mortality ~ Precip)
summary(mortality_precip)
mortality_Julytemp <- lm(Mortality ~ JulyTemp)
summary(mortality_Julytemp)
mortality_Over65 <- lm(Mortality ~ Over65 )
summary(mortality_Over65)
mortality_House <- lm(Mortality ~ House)
summary(mortality_House)
mortality_Nox <- lm(Mortality ~ NOX )
summary(mortality_Nox)
mortality_S02 <- lm(Mortality ~ SO2)
summary(mortality_S02)
mortality_precip_Julytemp <- lm(Mortality ~ Precip + JulyTemp)
summary(mortality_precip_Julytemp)
mortality_precip_Over65 <- lm(Mortality ~ Precip + Over65)
summary(mortality_precip_Over65)
mortality_precip_House <- lm(Mortality ~ Precip + House)
summary(mortality_precip_House)
mortality_precip_NOX <- lm(Mortality ~ Precip + NOX)
summary(mortality_precip_NOX)
mortality_precip_SO2 <- lm(Mortality ~ Precip + SO2)
summary(mortality_precip_SO2)
mortality_precip_SO2_julytemp <- lm(Mortality ~ Precip + SO2 + JulyTemp)
summary(mortality_precip_SO2_julytemp)
mortality_precip_SO2_Over65 <- lm(Mortality ~ Precip + SO2 + Over65)
summary(mortality_precip_SO2_Over65)
mortality_precip_SO2_House <- lm(Mortality ~ Precip + SO2 + House)
summary(mortality_precip_SO2_House)
mortality_precip_SO2_NOX <- lm(Mortality ~ Precip + SO2 + NOX)
summary(mortality_precip_SO2_NOX)
mortality_precip_SO2_Over65_JulyTemp <- lm(Mortality ~ Precip + SO2 + Over65 + JulyTemp)
summary(mortality_precip_SO2_Over65_JulyTemp)
mortality_precip_SO2_Over65_House <- lm(Mortality ~ Precip + SO2 + Over65 + House)
summary(mortality_precip_SO2_Over65_House)
mortality_precip_SO2_Over65_NOX <- lm(Mortality ~ Precip + SO2 + Over65 + NOX)
summary(mortality_precip_SO2_Over65_NOX)
#2 Backwards Elimination Model
mortality_full_model <- lm(Mortality ~ Precip + JulyTemp + Over65 + House + NOX + SO2)
summary(mortality_full_model)
mortality_model_without_NOX <- lm(Mortality ~ Precip + JulyTemp + Over65 + House + SO2)
summary(mortality_model_without_NOX)
mortality_model_without_NOX_House <- lm(Mortality ~ Precip + JulyTemp + Over65 + SO2)
summary(mortality_model_without_NOX_House)
mortality_model_without_NOX_House_Julytemp <- lm(Mortality ~ Precip + Over65 + SO2)
summary(mortality_model_without_NOX_House_Julytemp)
#3 Calculating Malo Cp
library(leaps)
predictors <- cbind(Precip, JulyTemp, Over65, House, NOX, SO2)
malocp <- leaps(predictors, Mortality, method = 'Cp')
malocp
cbind(malocp$Cp, malocp$which)
linearmodelwithlowestMaloCp <- lm(Mortality ~ Precip + JulyTemp + Over65 + SO2)
summary(linearmodelwithlowestMaloCp)
#5 Anova F-Test 
ANOVA <- aov(Mortality ~ Precip + Over65 + SO2)
summary(ANOVA)
plot(Mortality ~ Precip)
#10 Scatterplot 
plot(Precip, Mortality, main = 'Does your income affect your Mortality Rate?', xlab = 'Precipitation', ylab = 'Mortality', cex = 2)
points(Precip[Poor == 0], Mortality[Poor == 0], col = "red", cex = 2)
points(Precip[Poor == 1], Mortality[Poor == 1], col = "green", cex = 2)
legend("topright", pch = 19, 
       col = c("red", "green"), 
       legend = c("income under $3,000", "income greater than 3,000"))
#11 Linear Model with indicator variable
linearmodel <- lm(Mortality ~ Precip + Poor)
summary(linearmodel)
#13 Linear Model with both indicator variable and interaction/product term
linearmodel_with_interaction <- lm(Mortality ~ Precip + Poor + Precip * Poor)
summary(linearmodel_with_interaction)

