maze <- read.csv(file.choose(), header = TRUE)
attach(maze)
plot(maze)
par(family = 'serif', cex.main = 2, cex.lab = 2, cex.axis = 2, mar = c(5,5,4,2))
hist(time)
hist(height)
hist(width)
hist(order)

heightlm <- lm(time ~ height)
summary(heightlm)
widthlm <- lm(time ~ width)
summary(widthlm)
orderlm <- lm(time ~ order)
summary(orderlm)
plot(fitted(heightlm), resid(heightlm))
hist(resid(heightlm))
height_and_order <- lm(time ~ height + order)
summary(height_and_order)
height_and_width <- lm(time ~ height + width)
summary(height_and_width)
width_and_order <- lm(time ~ width + order)
summary(width_and_order)
height_width_order <- lm(time ~ width + order + height)
summary(height_width_order)
summary(lm(height ~ width))
summary(lm(height ~ order))
summary(lm(width ~ order))
install.packages("leaps")
library(leaps)

predictors <- cbind(height,width, order)
bestCplm <- leaps(predictors, time, method = 'Cp')
bestCplm
cbind(bestCplm$Cp, bestCplm$which)

bestRSAlm <- leaps(predictors, time, method = 'adjr2')
cbind(bestRSAlm$adjr2, bestRSAlm$which)


