mlb <- read.csv(file.choose(), header = TRUE)
attach(mlb)
winpct_HR <- lm(WinPct ~ HR)
summary(winpct_HR)
winpct_Doubles <- lm(WinPct ~ Doubles)
summary(winpct_Doubles)
winpct_hitsallowed <- lm(WinPct ~ HitsAllowed)
summary(winpct_hitsallowed)
winpct_strikeouts <- lm(WinPct ~ StrikeOuts)
summary(winpct_strikeouts)
winpct_obp <- lm(WinPct ~ OBP)
summary(winpct_obp)
winpct_obp_hr <- lm(WinPct ~ OBP + HR)
summary(winpct_obp_hr)
winpct_obp_doubles <- lm(WinPct ~ OBP + Doubles)
summary(winpct_obp_doubles)
winpct_obp_hitsallowed <- lm(WinPct ~ OBP + HitsAllowed)
summary(winpct_obp_hitsallowed)
winpct_obp_strikeouts <- lm(WinPct ~ OBP + StrikeOuts)
summary(winpct_obp_strikeouts)
winpct_obp_hitsallowed_HR <- lm(WinPct ~ OBP + HitsAllowed + HR)
summary(winpct_obp_hitsallowed_HR)
winpct_obp_hitsallowed_doubles <- lm(WinPct ~ OBP + HitsAllowed + Doubles)
summary(winpct_obp_hitsallowed_doubles)
winpct_obp_hitsallowed_strikeouts <- lm(WinPct ~ OBP + HitsAllowed + StrikeOuts)
summary(winpct_obp_hitsallowed_strikeouts)
big_model <- lm(WinPct ~ HR + Doubles + HitsAllowed + StrikeOuts + OBP)
summary(big_model)
model2 <- lm(WinPct ~ HR + HitsAllowed + StrikeOuts + OBP)
summary(model2)
model3 <- lm(WinPct ~ HR + HitsAllowed + OBP)
summary(model3)
model4 <- lm(WinPct ~ HitsAllowed + OBP)
summary(model4)
library(leaps)
predictors <- cbind(HR, Doubles, HitsAllowed, StrikeOuts, OBP)
malocp <- leaps(predictors, WinPct, method = 'Cp')
malocp
cbind(malocp$Cp, malocp$which)
adjustedr <- leaps(predictors, WinPct, method = 'adjr2')
cbind(adjustedr$adjr2, adjustedr$which)
